version: "3"
services:
  postgres_db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./tests/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
      POSTGRES_DB: "test_db"

  mysql_db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./tests/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_password"
      MYSQL_DATABASE: "test_db"

  app:
    build: .
    volumes:
      - ./:/app
    links:
      - "postgres_db"
      - "mysql_db"
    depends_on:
      - "postgres_db"
      - "mysql_db"
    command: >
      bash -c "
      until mysqladmin ping -h mysql_db --user=db_user --password=db_password --silent; do sleep 2s; done &&
      python -u -m unittest discover -s tests -v
      "
