version: "3"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./tests/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
      POSTGRES_DB: "test_db"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./tests/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_password"
      MYSQL_DATABASE: "test_db"
